name = "AdaGP"
uuid = "3ed8efa5-706a-4739-9884-79022218f524"
authors = ["Nikos Gianniotis <ngiann@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
JuliaDemoGP = "53ca922f-95ab-4814-be4f-2c2ccfc107cd"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
